/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.3/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_compactnorenumber1();
extern bool test_compactmerge1();
extern bool test_compactmultichunks1();
